# Site settings
title: Tim Schott
email: timcschott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineer, NLP-enthusiast and Beach Boys fan.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://timschott.com" # the base hostname & protocol for your site
twitter_username: WashingtonBezos
linkedin_username: timothy-schott
github_username: timschott

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Software Engineer"
excerpt_separator: "<!--more-->"

plugins:
  - jekyll-sitemap

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""